version: "3.8"

networks:
  demo-net:
    driver: bridge

services:
  login:
    build: ./login-service
    ports:
      - "3001:3000"         # host:container
    networks:
      - demo-net

  order:
    build: ./order-service
    ports:
      - "3002:3000"
    networks:
      - demo-net

  inventory:
    build: ./inventory-service
    ports:
      - "3003:3000"
    networks:
      - demo-net

  frontend:
    build: ./frontend-service    
    ports:
      - "8080:3000"
    depends_on:
      - login
      - order
      - inventory
    networks:
      - demo-net
