version: "3.8"

networks:
  demo-net:
    driver: bridge

services:
  login:
    build: ./login-service
    environment:
      - PORT=80              # tell Express to listen on 80
    ports:
      - "3001:80"            # map host 3001 → container 80
    networks:
      - demo-net

  order:
    build: ./order-service
    environment:
      - PORT=80
    ports:
      - "3002:80"
    networks:
      - demo-net

  inventory:
    build: ./inventory-service
    environment:
      - PORT=80
    ports:
      - "3003:80"
    networks:
      - demo-net

  frontend:
    build: ./frontend-service
    environment:
      - PORT=80
    ports:
      - "8080:80"
    depends_on:
      - login
      - order
      - inventory
    networks:
      - demo-net
