version: "3.8"
services:
  login:
    build: ./login-service
    networks:
      - demo-net

  order:
    build: ./order-service
    networks:
      - demo-net

  inventory:
    build: ./inventory-service
    networks:
      - demo-net

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - login
      - order
      - inventory
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
